<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<div class="row-fluid" id="footer-blue">
	<div class="container">
		<div class="row">
			<div class="col-md-12 center">
				<h3 class="center tittle-section-w">Mais Vendidos</h3>
				<img src="/skin/frontend/mytheme/default/images/teste.png" />
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 center">
				<h3 class="center tittle-section-w">Destaques</h3>
				<img src="/skin/frontend/mytheme/default/images/teste.png" />
			</div>
		</div>
	</div>
</div>
<div class="row-fluid" id="footer-orange">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-md-offset-2">
				<img src="/skin/frontend/mytheme/default/images/log-news.jpg" />
			</div>
		</div>
	</div>
</div>
<div class="container" id="footer-white">
	<div class="row">
		<div class="col-md-10 col-md-offset-1" style="margin-bottom: 40px;border-bottom: 1px solid #cccccc;padding-bottom: 40px;">
			<div class="row">
				<div class="col-md-4">
					<h4 class="title-footer">BARTH GAMES</h4>
					<ul>
						<li>Rua XV de Novembro, 420</li>
						<li>Centro  |  CEP 80020-310</li>
						<li>Curitiba  |  PR</li>
						<li>Fone: (41) 3232-8219</li>
						<li style="margin-top: 40px; margin-bottom: 20px"><a href="#"><img src="/skin/frontend/mytheme/default/images/veja_mapa.jpg"></a></li>
						<li>
							<a href="#" style="margin-left: 0" class="s-icon icon-fb-b"></a>
                            <a href="#" class="s-icon icon-tw-b"></a>
                            <a href="#" class="s-icon icon-it-b"></a>
						</li>
					</ul>
				</div>
				<div class="col-md-4">
					<h4 class="title-footer">INSTITUCIONAL</h4>
					<?php echo $this->getChildHtml() ?>
				</div>
				<div class="col-md-4">
					<h4 class="title-footer">LOJA</h4>

				</div>
			</div>
		</div>
	</div>
</div>
<div class="container" id="footer-master">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="row">
				<div class="col-md-4">
					<img src="/skin/frontend/mytheme/default/images/pagamento.jpg"/>
				</div>
				<div class="col-md-4">
					<img src="/skin/frontend/mytheme/default/images/entrega.jpg"/>
				</div>
				<div class="col-md-4">
					<img src="/skin/frontend/mytheme/default/images/seguro.jpg"/>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container" id="footer-white">
	<div class="row">
		<div class="col-md-10 col-md-offset-1" style="margin-bottom: 40px;border-bottom: 1px solid #cccccc;padding-bottom: 40px;">