<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="row" id="bgtop">
    <div class="container">
        <header role="banner" class="row">
            <div class="col-md-2">
                <h1 class="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
            </div>
            <div class="col-md-10">
                <div class="row">
                    <div class="col-md-12" id="topLinks">
                        <?php echo $this->getChildHtml('topLinks') ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-8">
                            <?php echo $this->getChildHtml('topSearch') ?>
                        </div>
                        <div class="col-md-2">
                            <?php
                                $count = $this->helper('checkout/cart')->getSummaryCount();  //get total items in cart
                                $total = $this->helper('checkout/cart')->getQuote()->getGrandTotal(); //get total price
                                if($count==0) {
                                    echo $this->__('<a href="/checkout/cart" class="cartgo">0</a>',$count);
                                } else {
                                    echo $this->__('<a href="/checkout/cart" class="cartgo">%s</a>',$count);
                                }
                            ?>
                        </div>
                        <div class="col-md-2">
                            <a href="#" class="s-icon icon-fb"></a>
                            <a href="#" class="s-icon icon-tw"></a>
                            <a href="#" class="s-icon icon-it"></a>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </div>
</div>
<?php echo $this->getChildHtml('topMenu') ?>
